name = "jittered-voronoi"
version = "0.1.0"
keywords = ["math"]
license = "MIT"
licenseFiles = ["LICENSE"]
defaultTargets = ["JitteredVoronoi"]

[leanOptions]
pp.unicode.fun = true
autoImplicit = false
relaxedAutoImplicit = false

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.33.0"

[[lean_lib]]
name = "JitteredVoronoi"
